allowBuilds:
  better-sqlite3: true
  esbuild: true
  sharp: true
  workerd: true
catalog:
  "@types/node": ^25.6.0
  vite: npm:@voidzero-dev/vite-plus-core@0.3.0
  vite-plus: 0.3.0
  void: 0.10.12
minimumReleaseAgeExclude:
  - vite-plus
  - "@voidzero-dev/vite-plus-*"
  - void@0.10.8
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
