catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.1.18-alpha.0
  vite-plus: 0.1.18-alpha.0
  vitest: npm:@voidzero-dev/vite-plus-test@0.1.18-alpha.0
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
